---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: k8s-openstack
data:
  OS_PROJECT_DOMAIN_NAME: default
  OS_USER_DOMAIN_NAME: default
  OS_PROJECT_NAME: admin
  OS_USERNAME: admin
  OS_AUTH_URL: 'http://openstack-keystone:5000/v3'
  OS_IDENTITY_API_VERSION: '3'
  OS_IMAGE_API_VERSION: '2'
  PS1: '\u@\h \W(keystone)\$'
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
  namespace: k8s-openstack
type: Opaque
data:
  OS_PASSWORD: dktJNThRRzU3Z2RkRUxqSQ==
  # vKI58QG57gddELjI
